### ISSUE TITLE
Verbetering [DO3]: Feedback standaard op invalid?

### ISSUE THREAD

**Issue by arothuis-hu** [RaymonvdBrink/lingo-raymon#3]
Kan je dit oplossen zonder de feedback standaard op `INVALID` te zetten? 

https://github.com/RaymonvdBrink/lingo-raymon/blob/9a73d29515b73a0ec3ebea657003bd50b0a3faad/src/main/java/nl/hu/cisq1/lingo/trainer/domain/Game.java#L44-L53

Waarschijnlijk hoef je bij het starten van een ronde zelfs nog geen feedback bij te houden.

**Comment by RaymonvdBrink** [comment]
verwerk in laaste push
